# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EyeTrackTest' do
  # Comment the next line if you
 use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  #pod 'LTScrollView'
  ∫#pod 'SwiftMessages','~> 4.1.4'
  pod 'HandyJSON', '~> 5.0.0-beta.1'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SQLite.swift'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'SGPagingView'
  pod 'BMPlayer'
  pod 'FDFullscreenPopGesture'
  # pod 'Texture'
  pod 'lottie-ios'

end
